### ISSUE TITLE
The Store for this customer account does not match the store on the order.

### ISSUE THREAD

**Issue by Slimzash** [PromInc/Magento-1.x-Link-Customer-to-Order#7]
"Reset the link parameters to ensure the store for the customer search matches the store of the order."

Can you please explain to me how I can go about doing this? I have been having a weird issue on my website (Magento) that sometimes deletes the users account but all the orders stay with no explanation. In the mean time I have been reconnecting these by creating their accounts again and manually attaching their old orders. Sometimes I get the error above though, how do I get by it?

thanks in advance!

**Comment by PromInc** [comment]
Sounds like an ugly bug in your codebase!  Yikes!

FYI - the delete customer action by default will leave the order history by design.  That allows you to keep the financial and stock history, but as you know the customer records and link to an order goes away.

That error message is shown when the customer (from the customer table - not the order history) is not a guest AND the store ID on the order does not match the store ID for the customer.

https://github.com/PromInc/Magento-1.x-Link-Customer-to-Order/blob/master/app/code/local/Prominc/PromincLinkOrder/Block/Adminhtml/Admin/Preview.php#L145
```
    if( $customer->getIsGuest() != 1 && $customer->getStoreId() != $order->getStoreId() ) {
      /* Error Checking | Order Store and Customer Store Do Not Match */
      $searchForLinkUrl = Mage::helper('adminhtml')->getUrl('*/prominclinkorder_prominclinkorderadmin/', array('s' => $this->getData('store'), 'e' => $this->getData('email'), 'o' => $this->getData('order')));
      $canLink['canLink'] = false;
      $canLink['explanation'][] = '<p>The <b>Store</b> for this customer account does not match the store on the order.</p><p>Reset the link parameters to ensure the store for the customer search matches the store of the order.</p><p><a href="'.$searchForLinkUrl.'">Update Search</a></p>';
    }
```

My assumption is that your customer is not set to the store ID that the order was placed from.

If you run multiple stores under your installation this could be an easy mistake to set the customer to the wrong store.  If not, keep in mind that with Magento, store ID 0 is the admin.  There could be a possibility that the order was set to store ID 0 on the sales_flat_order table.  It shouldn't have been, but there's a possibility...

I hope this helps get you in the right direction.
